spring:
  profiles:
    active: localhost
---
spring:
  profiles: localhost
  datasource:
    primary:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/bookshelf
      username: test
      password: test
    secondary:
      driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
      url: jdbc:sqlserver://WAKA-VJS1321\SQLEXPRESS01;databaseName=bookshelf3
      username: test3
      password: test3
---
spring:
  profiles: docker
  datasource:
    primary:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://mysql:3306/bookshelf
      username: test
      password: test
    secondary:
      driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
      url: jdbc:sqlserver://WAKA-VJS1321\SQLEXPRESS01;databaseName=bookshelf3
      username: test3
      password: test3
---
spring:
  profiles: docker2
  datasource:
    primary:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://mysql:3306/bookshelf
      username: test
      password: test
    secondary:
      driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
      url: jdbc:sqlserver://WAKA-VJS1321\SQLEXPRESS01;databaseName=bookshelf3
      username: test3
      password: test3